[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' https://ka-f.fontawesome.com fonts.gstatic.com https://plausible.monocletiger.eu https://fonts.googleapis.com app.netlify.com https://blog.rogertmiller.com https://kit.fontawesome.com/addc70342f.js https://plausible.monocletiger.eu/api/event;"
    Cache-Control = "public, max-age=800"
    access-control-allow-credentials = "true"
    Cross-Origin-Resource-Policy = "false" 
    Referrer-Policy = "origin-when-cross-origin"
