[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = '''
    content-src 'self' blog.rogertmiller.com;
    connect-src https://plausible.monocletiger.eu https://ka-f.fontawesome.com;
    script-src-elem https://plausible.monocletiger.eu https://ka-f.fontawesome.com;
    default-src 'self' 'unsafe-inline'
    https://ka-f.fontawesome.com
    fonts.gstatic.com
    plausible.monocletiger.eu
    https://fonts.googleapis.com app.netlify.com
    https://blog.rogertmiller.com
    https://kit.fontawesome.com/addc70342f.js
    https://plausible.monocletiger.eu/api/event;
    script-src 'self' 'unsafe-inline' plausible.monocletiger.eu
    https://kit.fontawesome.com/addc70342f.js
    https://plausible.monocletiger.eu/js/script.js;'''
