[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' fonts.gstatic.com plausible.monocletiger.eu https://fonts.googleapis.com app.netlify.com https://travel.rogertmiller.com https://plausible.monocletiger.eu/api/event;"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=34800"
    access-control-allow-credentials = "true"
    Cross-Origin-Resource-Policy = "cross-origin" 
    Referrer-Policy = "origin-when-cross-origin"
